swagger: "2.0"
info:
  version: "0.0.1"
  title: Chroma Rest API
# during dev, should point to your local machine
host: localhost:54235
# basePath prefixes all resource paths 
basePath: /chromasdk
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /heartbeat:
    # binds a127 app logic to a route
    x-swagger-router-controller: heartbeat
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: heartbeat
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
  /effect:
    # binds a127 app logic to a route
    x-swagger-router-controller: effect
    put:
      description: Setting effect with an identifier or set of identifiers.
      # used as the method name of the controller
      operationId: putEffect
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectIdentifierInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectIdentifierResponse"
    delete:
      description: Deleting an effect or a set of effects with identifier. Effects must be deleted to free resources.
      # used as the method name of the controller
      operationId: deleteEffect
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectIdentifierArrayInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (DELETE)
          schema:
            $ref: "#/definitions/EffectIdentifierResponse"
  /chromalink:
    # binds a127 app logic to a route
    x-swagger-router-controller: chromalink
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putChromaLink
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postChromaLink
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"     
  /headset:
    # binds a127 app logic to a route
    x-swagger-router-controller: headset
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putHeadset
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postHeadset
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"     
  /keyboard:
    # binds a127 app logic to a route
    x-swagger-router-controller: keyboard
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putKeyboard
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postKeyboard
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"      
  /keypad:
    # binds a127 app logic to a route
    x-swagger-router-controller: keypad
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putKeypad
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postKeypad
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"      
  /mouse:
    # binds a127 app logic to a route
    x-swagger-router-controller: mouse
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putMouse
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postMouse
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /mousepad:
    # binds a127 app logic to a route
    x-swagger-router-controller: mousepad
    put:
      description: To turn off effect use CHROMA_NONE.
      # used as the method name of the controller
      operationId: putMousepad
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: POST will return an effect id. To turn off effect use CHROMA_NONE.
      operationId: postMousepad
      parameters:
        - in: body
          name: data
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  EffectType:
    type: string
    enum: 
      - CHROMA_NONE
      - CHROMA_WAVE
      - CHROMA_SPECTRUMCYCLING
      - CHROMA_BREATHING
      - CHROMA_BLINKING
      - CHROMA_REACTIVE
      - CHROMA_STATIC
      - CHROMA_CUSTOM
      - CHROMA_RESERVED
      - CHROMA_INVALID
    description: Chroma generic effects. Note that not all devices supported the listed effects
  EffectInput:
    type: object
    description: JSON Data
    required:
      - effect
    properties:
      effect:
        $ref: "#/definitions/EffectType"            
      param:
        type: object
        description: Effect definition
        properties:
          color:
            type: integer
            description: Color value in BGR format
  EffectResponseId:
    required:
      - result
    properties:
      id:
        type: string
      result:
        type: integer
  EffectResponse:
    required:
      - result
    properties:
      result:
        type: integer
  EffectIdentifierInput:
    properties:
      id:
        type: string
      ids:
        type: array
        items:
          type: string
  EffectIdentifierArrayInput:
    properties:
      ids:
        type: array
        items:
          type: string
  EffectIdentifierResponse:
    properties:
      result:
        type: integer
      results:
        type: array
        items:
          type: object
          properties:
            result:
              type: integer
