swagger: "2.0"
info:
  version: "0.0.1"
  title: Chroma Rest API
# during dev, should point to your local machine
host: localhost:80
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /chromasdk/keyboard:
    # binds a127 app logic to a route
    x-swagger-router-controller: keyboard
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putKeyboard
      parameters:
        - in: body
          name: keyboardInput
          schema:
            $ref: "#/definitions/KeyboardInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/KeyboardResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postKeyboard
      parameters:
        - in: body
          name: keyboardInput
          schema:
            $ref: "#/definitions/KeyboardInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/KeyboardResponseId"            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  EffectType:
    type: string
    enum: 
      - CHROMA_NONE
      - CHROMA_WAVE
      - CHROMA_SPECTRUMCYCLING
      - CHROMA_BREATHING
      - CHROMA_BLINKING
      - CHROMA_REACTIVE
      - CHROMA_STATIC
      - CHROMA_CUSTOM
      - CHROMA_RESERVED
      - CHROMA_INVALID
    description: Chroma generic effects. Note that not all devices supported the listed effects
  KeyboardInput:
    type: object
    description: JSON Data
    required:
      - effect
    properties:
      effect:
        $ref: "#/definitions/EffectType"            
      param:
        description: 2 dimensional array of size 6 rows by 22 columns. Each cell contains the color value in BGR format
        type: array
        items:
          type: array
          items:
            type: integer
      color:
        description: 6 by 22 columns of array containing the value of color in BGR format
        type: array
        items:
          type: integer
      key:
        description: 6 by 22 columns of array containing the value of color on the specific key at the location in BGR format. Specify a bit mask of 0x01000000 with the color value for each keys that has an effect.
        type: array
        items:
          type: integer
  KeyboardResponseId:
    properties:
      id:
        type: string
      result:
        type: integer
      results:
        type: array
        items:
          "$ref": "#/definitions/KeyboardResponseItemId"
  KeyboardResponseItemId:
    properties:
      id:
        type: string
      result:
        type: integer
  KeyboardResponse:
    properties:
      result:
        type: integer