swagger: "2.0"
info:
  version: "0.0.1"
  title: Chroma Rest API
# during dev, should point to your local machine
host: localhost:54235
# basePath prefixes all resource paths 
basePath: /chromasdk
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /chromalink:
    # binds a127 app logic to a route
    x-swagger-router-controller: chromalink
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putChromaLink
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 1 rows by 5 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postChromaLink
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 1 rows by 5 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /headset:
    # binds a127 app logic to a route
    x-swagger-router-controller: headset
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putHeadset
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 9 rows by 7 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postHeadset
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 9 rows by 7 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /keyboard:
    # binds a127 app logic to a route
    x-swagger-router-controller: keyboard
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putKeyboard
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 6 rows by 22 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postKeyboard
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 6 rows by 22 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /keypad:
    # binds a127 app logic to a route
    x-swagger-router-controller: keypad
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putKeypad
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 4 rows by 5 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postKeypad
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 4 rows by 5 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"   
  /mouse:
    # binds a127 app logic to a route
    x-swagger-router-controller: mouse
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putMouse
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 9 rows by 7 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postMouse
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 9 rows by 7 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /mousepad:
    # binds a127 app logic to a route
    x-swagger-router-controller: mousepad
    put:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      # used as the method name of the controller
      operationId: putMousepad
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 1 rows by 15 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (PUT)
          schema:
            $ref: "#/definitions/EffectResponse"
    post:
      description: To create a custom effect use CHROMA_CUSTOM and fill in the colors in each element in the array.
      operationId: postMousepad
      parameters:
        - in: body
          name: effectInput
          description: Array dimensions are 1 rows by 15 columns.
          schema:
            $ref: "#/definitions/EffectInput"
      responses:
        # responses may fall through to errors
        default:
          description: Response (POST)
          schema:
            $ref: "#/definitions/EffectResponseId"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  EffectType:
    type: string
    enum: 
      - CHROMA_NONE
      - CHROMA_WAVE
      - CHROMA_SPECTRUMCYCLING
      - CHROMA_BREATHING
      - CHROMA_BLINKING
      - CHROMA_REACTIVE
      - CHROMA_STATIC
      - CHROMA_CUSTOM
      - CHROMA_RESERVED
      - CHROMA_INVALID
    description: Chroma generic effects. Note that not all devices supported the listed effects
  EffectInput:
    type: object
    description: JSON Data
    required:
      - effect
    properties:
      effect:
        $ref: "#/definitions/EffectType"            
      param:
        description: Two-dimensional color array. See method for dimension details.
        type: array
        items:
          type: array
          items:
            type: integer
      color:
        description: Two-dimensional color array. See method for dimension details.
        type: array
        items:
          type: integer
      key:
        description: Two-dimensional color array. See method for dimension details.
        type: array
        items:
          type: integer
  EffectResponseId:
    properties:
      id:
        type: string
      result:
        type: integer
      results:
        type: array
        items:
          "$ref": "#/definitions/EffectResponseItemId"
  EffectResponseItemId:
    properties:
      id:
        type: string
      result:
        type: integer
  EffectResponse:
    properties:
      result:
        type: integer